import './globals.css'
import React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import {Inter} from 'next/font/google'
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {itdesignTheme} from "@/app/theme";
import Toolbar from "@mui/material/Toolbar";
import {Box} from "@mui/material";
import IconButton from "@mui/material/IconButton";
import HelpIcon from "@mui/icons-material/Help";
import AppBar from "@mui/material/AppBar";
import Container from "@mui/material/Container";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={itdesignTheme}>
            <CssBaseline />
            <AppBar position="static" color="transparent">
              <Toolbar>
                <Box sx={{flexGrow: 1,
                  alignItems: "center",
                  display: "flex",}}>
                  Calcultor With Regular Expression
                </Box>
                <a
                  target="_blank"
                  rel="noreferrer"
                  href="#"
                >
                  <IconButton>
                    <HelpIcon />
                  </IconButton>
                </a>
              </Toolbar>
            </AppBar>
            <Container
              data-testid="layout"
              maxWidth="sm"
              sx={{ marginTop: 2, marginBottom: 2 }}
            >
            {children}
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
